// PROJECT GLOBALS


// EXPRESS GLOBALS
const ADD_LIST = "addList"
const UPDATE_LIST = "updateList"
const UPDATE_LIST_NAME = "updateListName"
const REMOVE_LIST = "removeList"
const ADD_PRODUCT_LIST = "addProductList"
const LIST_PRODUCT_SELECTED = "listProductSelected"
const REMOVE_PRODUCT_LIST = "removeProductList"


// MONGODB GLOBALS
const USER_DB = "BazaaraUsers"
const USER_COLLECTION = "UserCollection"
const PRODUCTS_DB = "BazaaraGrocery"
const PRODUCTS_COLLECTION = "GroceryCollection"

exports.ADD_LIST = ADD_LIST
exports.UPDATE_LIST = UPDATE_LIST
exports.UPDATE_LIST_NAME = UPDATE_LIST_NAME
exports.REMOVE_LIST = REMOVE_LIST
exports.ADD_PRODUCT_LIST = ADD_PRODUCT_LIST
exports.LIST_PRODUCT_SELECTED = LIST_PRODUCT_SELECTED
exports.REMOVE_PRODUCT_LIST = REMOVE_PRODUCT_LIST

exports.USER_DB = USER_DB
exports.USER_COLLECTION = USER_COLLECTION
exports.PRODUCTS_DB = PRODUCTS_DB
exports.PRODUCTS_COLLECTION = PRODUCTS_COLLECTION